#include "../includes/ErrorResponseBuilder.hpp"
#include "../includes/StaticFileHandler.hpp"

HttpResponse ErrorResponseBuilder::buildErrorResponse(int code,
													  const ServerConfig &config) {
	std::map<int, std::string>::const_iterator ep = config.error_pages.find(code);
	if (ep != config.error_pages.end()) {
		HttpResponse custom = StaticFileHandler::serveStatic(ep->second);
	if (custom.statusCode == 200) {
		custom.setStatus(code);
			return custom;
		}
	}
	return _defaultErrorResponse(code); // fallback basic .html response in case static page error missing or no permissions
}

// if custom err page exists is used, otherwise default body is generated by _errorBody() and uses this text as body: will see this in browser 
HttpResponse ErrorResponseBuilder::_defaultErrorResponse(int code) {
	switch (code) {
		case 400: return HttpResponse::make_400();
		case 403: return HttpResponse::make_403();
		case 404: return HttpResponse::make_404();
		case 405: return HttpResponse::make_405();
		case 408: return HttpResponse::make_408();
		case 413: return HttpResponse::make_413();
		default: return HttpResponse::make_500();
	}
}
