#include "../includes/HttpResponse.hpp"
#include <ctime>
#include <sstream>

// headers and body are default-constructed empty by std::map and std::string automatically.
HttpResponse::HttpResponse() : statusCode(200) {}

// ── setters ──────────────────────────────────────────────────────────

HttpResponse &HttpResponse::setStatus(int code) {
    statusCode = code;
    return *this; // this is a pointer to the current object, *this is the object itself. Returning *this allows method chaining, e.g., resp.setStatus(404).setBody("Not found");
}

HttpResponse &HttpResponse::setHeader(const std::string &key, const std::string &value) {
    headers[key] = value;
    return *this;
}

HttpResponse &HttpResponse::setBody(const std::string &content, const std::string &type) {
    body = content;
    headers["Content-Type"]   = type;
    headers["Content-Length"] = std::to_string(content.size());
    return *this;
}

// ── static builders ───────────────────────────────────────────────────────────

HttpResponse HttpResponse::make_200(const std::string &body,
                                    const std::string &type) {
    HttpResponse r;
    r.setStatus(200).setBody(body, type);
    return r;
}

HttpResponse HttpResponse::make_redirect(int code, const std::string &location) {
    HttpResponse r;
    int redirectCode = (code == 301) ? 301 : 302;
    r.setStatus(redirectCode);
    r.setHeader("Location", location);
    r.setHeader("Content-Length", "0");
    return r;
}

//After the function returns, the local r is destroyed, but the returned value is valid and independent.
HttpResponse HttpResponse::make_400() {
    HttpResponse r;
    r.setStatus(400).setBody(_errorBody(400, "Bad Request"));
    return r;
}

// if custom err page exists is used, otherwise default body is generated by _errorBody() and uses this text as body
HttpResponse HttpResponse::make_403() {
    HttpResponse r;
    r.setStatus(403).setBody(_errorBody(403, "Forbidden"));
    return r;
}

HttpResponse HttpResponse::make_404() {
    HttpResponse r;
    r.setStatus(404).setBody(_errorBody(404, "Not Found"));
    return r;
}

HttpResponse HttpResponse::make_405() {
    HttpResponse r;
    r.setStatus(405).setBody(_errorBody(405, "Method Not Allowed"));
    return r;
}

HttpResponse HttpResponse::make_408() {
    HttpResponse r;
    r.setStatus(408).setBody(_errorBody(408, "Request Timeout"));
    return r;
}

HttpResponse HttpResponse::make_413() {
    HttpResponse r;
    r.setStatus(413).setBody(_errorBody(413, "Payload Too Large"));
    return r;
}

HttpResponse HttpResponse::make_415() {
    HttpResponse r;
    r.setStatus(415).setBody(_errorBody(415, "Unsupported Media Type"));
    return r;
}

HttpResponse HttpResponse::make_409() {
    HttpResponse r;
    r.setStatus(409).setBody(_errorBody(409, "Conflict"));
    return r;
}

HttpResponse HttpResponse::make_500() {
    HttpResponse r;
    r.setStatus(500).setBody(_errorBody(500, "Internal Server Error"));
    return r;
}

/* 501 Not Implemented: the request method is a valid HTTP verb but this server
   does not support it at all (e.g. PATCH, TRACE, OPTIONS).
   Different from 405: 405 means "not allowed on this path", 501 means "not
   supported anywhere". */
HttpResponse HttpResponse::make_501() {
    HttpResponse r;
    r.setStatus(501).setBody(_errorBody(501, "Not Implemented"));
    return r;
}

/* 504 Gateway Timeout: an upstream process (here: a CGI script) did not
   produce output within the allowed time. The server itself is running fine —
   the timeout is on the child process, not on the client connection.
   Different from 408: 408 is the client timing out, 504 is the backend. */
HttpResponse HttpResponse::make_504() {
    HttpResponse r;
    r.setStatus(504).setBody(_errorBody(504, "Gateway Timeout"));
    return r;
}

/**
 *  ── serialize — builds full HTTP/1.1 message for send() ─────────────────
 Format produced:
   1) Status line:   "HTTP/1.1 <code> <reason>\r\n"
   2) Header lines:  "Key: Value\r\n" for each header map entry
   3) Header/body separator: "\r\n"
   4) Body bytes appended as-is
 The returned string is a complete response payload ready for socket send().

 RFC 7231 requires every HTTP/1.1 server to include a Date header in every response.
 */

std::string HttpResponse::serialize() const {
    std::string reason = _reason(statusCode);

    std::ostringstream oss;
    oss << "HTTP/1.1 " << statusCode << " " << reason << "\r\n";

    if (headers.find("Date") == headers.end()) {
        char datebuf[64];
        time_t now = time(nullptr);
        struct tm *gmt = gmtime(&now);
        strftime(datebuf, sizeof(datebuf), "%a, %d %b %Y %H:%M:%S GMT", gmt);
        oss << "Date: " << datebuf << "\r\n";
    }

    for (std::map<std::string,std::string>::const_iterator it = headers.begin();
         it != headers.end(); ++it)
        oss << it->first << ": " << it->second << "\r\n";

    oss << "\r\n" << body;
    return oss.str();
}

// ── private helpers ───────────────────────────────────────────────────────────

/* Maps a numeric HTTP status code to its standard reason phrase.
   The phrase appears in the status line: "HTTP/1.1 404 Not Found".
   RFC 9110 §8.1: the phrase is informational only — clients MUST use the
   numeric code for logic, not the text. But returning "Unknown" for codes
   the server actually sends signals a broken implementation to evaluators. */
std::string HttpResponse::_reason(int code) {
    switch (code) {
        case 200: return "OK";
        case 201: return "Created";           // resource was created (e.g. file upload)
        case 204: return "No Content";        // success with no body (e.g. DELETE)
        case 301: return "Moved Permanently";
        case 302: return "Found";
        case 400: return "Bad Request";
        case 409: return "Conflict";
        case 403: return "Forbidden";
        case 404: return "Not Found";
        case 405: return "Method Not Allowed";
        case 408: return "Request Timeout";
        case 413: return "Payload Too Large";
        case 415: return "Unsupported Media Type";
        case 500: return "Internal Server Error";
        case 501: return "Not Implemented";   // valid method the server never supports (e.g. PATCH)
        case 504: return "Gateway Timeout";   // CGI script did not respond in time
        default:  return "Unknown";
    }
}

/* returns the HTML body for an error response */
std::string HttpResponse::_errorBody(int code, const std::string &reason) {
    std::ostringstream oss;
    oss << "<html><body><h1>"
        << code << " " << reason
        << "</h1></body></html>";
    return oss.str();
}
