# =============================================================
#  default.conf  —  4 virtual servers, all plain HTTP
# =============================================================

# ─────────────────────────────────────────
# SERVER 1 — "one"  on port 8080
# ─────────────────────────────────────────
server {
    listen          8080;
    host            127.0.0.1;
    server_name     one;

    client_max_body_size    1048576;    # 1MB

    error_page      400     /www/errors/400.html;
    error_page      403     /www/errors/403.html;
    error_page      404     /www/errors/404.html;
    error_page      500     /www/errors/500.html;

    location / {
        root            ./www/one;
        index           /index.html;
        autoindex       on;
        allowed_methods GET POST;
    }

    location /zombie_kittens {
        root            ./www/one;
        index           /zombie_kittens.html;
        autoindex       off;
        allowed_methods GET;
    }

    location /play {
        return 301 /game_start;
    }

    location /game_start {
        root ./www/one/pages;
        index game_start.html;
        autoindex off;
        allowed_methods GET;
    }

    # File uploads
    location /upload {
        root            ./www/one;
        limit_except    POST;
        upload_enable   on;
        upload_path     ./www/uploads;
        client_max_body_size 5000000;
    }

    # Directory listing example
    location /files {
        root        ./www/one;
        autoindex   on;
        limit_except GET;
    }

    # CGI — Python
    location /cgi-bin {
        root            ./www/cgi-bin;
        limit_except    GET POST;
        cgi .py         /usr/bin/python3;
        cgi .php        /usr/bin/php-cgi;
    }

    # Redirect example
    location /old {
        return 301 /new;
    }

}
