# Server settings
host=127.0.0.1
port=8080
root=./www
index=index.html

# Error pages currently dont have them
error_404=./errors/404.html
error_500=./errors/500.html

# Max body size (bytes)
client_max_body_size=1048576

# Allowed methods
methods=GET,POST,DELETE

#server {
#  listen 8080;
#	server_name default_server;
#  root ./docs

#  error_page 400 /default_errors/error_400.html;
#	error_page 403 /default_errors/error_403.html;
#	error_page 404 /default_errors/error_404.html;
#	error_page 405 /default_errors/error_405.html;
#	error_page 408 /default_errors/error_408.html;
#  error_page 413 /default_errors/error_413.html;
#	error_page 500 /default_errors/error_500.html;

#  location / {
#    method GET POST ;
#    root ;
#    index index.html;
#  }
#}

#Nginx does not generate the page.
#It forwards the request to another server.


#Why companies do this

#Example architecture used by companies like Netflix.

#Reasons:

#security

#load balancing

#caching

#SSL termination

#Nginx sits in front of the application servers.

#server {
#    listen 80;
#    root /var/www/html;

#    location / {
#        index index.php index.html;
#    }

#    location ~ \.php$ {
#        fastcgi_pass 127.0.0.1:9000;
#        fastcgi_index index.php;
#        include fastcgi_params;
#    }
#}

#http://mysite.com/index.php
#Browser
# ↓
#Nginx
# ↓
#PHP-FPM (FastCGI)
# ↓
#PHP executes code
# ↓
#HTML returned
# ↓
#Nginx sends response

#Browser
#   ↓
#Nginx
#   ↓
#Application server
#   ↓
#Database

